source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ContainerViewManager_Example', :exclusive => true do
  pod 'ContainerViewManager', :path => '../'
end

target 'ContainerViewManager_Tests', :exclusive => true do
  pod 'ContainerViewManager', :path => '../'

  pod 'FBSnapshotTestCase'
end
