language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install fastlane
- gem install cocoapods
#- pod install --project-directory=Example

branches:
only:
-master

script:
- set -o pipefail
- ./fastlane/travis.sh
- pod lib lint
