default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
  	scan(
	  workspace: "ContainerViewManager.xcworkspace",
	  scheme: "ContainerViewManager",
	  clean: true,
	  code_coverage: true,
	  skip_build: true
	)

	xcov(
	  workspace: "ContainerViewManager.xcworkspace",
	  scheme: "ContainerViewManager"
	)
  end
end
